services:
  - type: web
    name: dimensy-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: VAPID_PUBLIC_KEY
        value: BNF2p8Dc2HHssHe0xHUQujcwu4R_aVzVC09kEshbUYeHS7anhHD_kEedvt2Tq6sSDzSQMYc1UKDzYp8r6jGgET4
      - key: VAPID_PRIVATE_KEY
        value: 79jQe5DZ-k-3yGcO9FArpkaX83qIo2hIUvqq8UFrlE4
      - key: VAPID_EMAIL
        value: mailto:contato@dimensy.com.br
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
